name: window_meas
description: "Windows measurement app for the construction industry."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  go_router: ^13.2.4
  intl: ^0.19.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  cached_network_image: ^3.2.3
  injectable: ^2.4.1
  get_it: ^7.6.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  path_provider: ^2.1.3
  uuid: ^4.4.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  replay_bloc: ^0.2.7
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.4
  json_serializable: ^6.6.2
  bloc_test: ^9.1.2
  mocktail: ^1.0.3
  injectable_generator: ^2.6.1
  isar_generator: ^3.1.0+1

dependency_overrides:
  analyzer: 6.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
